macbooktroops/Schedule-android

app/build.gradle
버전코드 규칙 추가
a.b.c.d
a는 메이져버전
b는 기능 10개 추가 or 많은 기능이 추가되었을시에
c는 테스트 관리용 버전
d는 기능 추가 or 버그 수정시 올리는 코드
=> [#162846022] Setting version code and name

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/playgilround/schedule/client/Activity/ScheCalendarActivity.java, app/src/main/java/com/playgilround/schedule/client/Dialog/ScheCalendarDialog.java, app/src/main/java/com/playgilround/schedule/client/ScheduleApplication.java, app/src/main/res/drawable/rounded_lightgreen.xml, app/src/main/res/layout/dialog_calendar.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, build.gradle
=> 캘린더 날짜 클릭 시 다이얼로그 표시

app/src/main/java/com/playgilround/schedule/client/ScheduleApplication.java, app/src/main/java/com/playgilround/schedule/client/model/Event.java, app/src/main/java/com/playgilround/schedule/client/model/ScheduleMigration.java, app/src/main/res/values-ko/strings.xml, app/src/main/res/values/strings.xml
RealmMigration File and event model
=> [#162858179] Add RealmMigration and event model

app/build.gradle, app/src/main/java/com/playgilround/schedule/client/retrofit/APIClient.java, app/src/main/java/com/playgilround/schedule/client/retrofit/BaseUrl.java, app/src/main/java/com/playgilround/schedule/client/retrofit/HolidayAPI.java, app/src/main/java/com/playgilround/schedule/client/retrofit/UserAPI.java
=> [Add] Add network library

app/build.gradle, app/src/main/java/com/playgilround/schedule/client/ScheduleApplication.java, app/src/main/java/com/playgilround/schedule/client/activity/AddScheduleActivity.java, app/src/main/java/com/playgilround/schedule/client/activity/ScheduleCalendarActivity.java, app/src/main/java/com/playgilround/schedule/client/activity/ScheduleInfoActivity.java, app/src/main/java/com/playgilround/schedule/client/activity/SetLocationActivity.java, app/src/main/res/layout/activity_location.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/confirm_cancel_btn.xml, app/src/main/res/layout/dialog_add_schedule.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
지금 위치 정보를 받아 온후에, 스케줄 저장 시 Realm Schedule Table 에 저장.
=> String Resource 정리 및, Location, Latitude, Longitude 관련 작업

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/playgilround/schedule/client/activity/AddScheduleActivity.java, app/src/main/res/values-ko/strings.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
* 스케줄 저장 시 내용도 저장.
* 저장 된 스케줄 날짜 변경 시, 변경 된 날짜로 화면 표시
* 해당 날짜에 스케줄이 저장되있는지 확인을 위해 DateTime(JodaTime) 을 이용해 원하는 포맷으로 얻기.
* TimePicker 관련 Gradle 추가
(https://i.stack.imgur.com/3LUos.png 이런 형태 TimePicker도 있지만, 개인적으로 쌉불편해서 ㅋㅋ 전에 찾던 괜찮은 TimePicker가 있어서 일단 그거 추가했어용~~)
=> 선택된 날짜 DateTime 작업, TimePickerDIalog 추가.

app/src/main/java/com/playgilround/schedule/client/ScheduleApplication.java, app/src/main/java/com/playgilround/schedule/client/activity/AddScheduleActivity.java, app/src/main/java/com/playgilround/schedule/client/activity/ScheduleCalendarActivity.java, app/src/main/java/com/playgilround/schedule/client/model/Schedule.java, app/src/main/java/com/playgilround/schedule/client/model/ScheduleMigration.java, app/src/main/res/values/strings.xml
스케줄 날짜 지정 할 경우 CalendarDialog -> TimePickerDialog 순
JodaTime, SimpleDateFormat 이용해서 필요한 포맷으로 변환
Schedule Table 에 date 추가 후 schema 버전 2로 증가.
현재 표시 된 달 기준으로 저장된 스케줄 찾기 추가.
=> * 시간 설정 관련 작업, Schedule table schemaVersion 2..

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/playgilround/schedule/client/activity/LoginActivity.java, app/src/main/java/com/playgilround/schedule/client/activity/RegisterActivity.java, app/src/main/java/com/playgilround/schedule/client/activity/ScheduleCalendarActivity.java, app/src/main/res/layout/activity_regist.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values/strings.xml
Dex 에러? 발생해서 build.gradle 에 MultiDexEnable true 추가
SignUp 화면 기능제외하고 구성완료
=> MultiDexEnable, SignUp 기능 제외 화면구성

app/src/main/AndroidManifest.xml, app/src/main/java/com/playgilround/schedule/client/activity/MainActivity.java, app/src/main/java/com/playgilround/schedule/client/activity/ScheduleCalendarActivity.java, app/src/main/java/com/playgilround/schedule/client/activity/ScheduleInfoActivity.java, app/src/main/java/com/playgilround/schedule/client/adapter/ScheduleCardAdapter.java, app/src/main/java/com/playgilround/schedule/client/model/ScheduleCard.java, app/src/main/res/layout/activity_calendar.xml, app/src/main/res/layout/activity_location.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_regist.xml, app/src/main/res/layout/confirm_cancel_btn.xml, app/src/main/res/layout/current_date.xml, app/src/main/res/layout/dialog_add_schedule.xml, app/src/main/res/layout/dialog_calendar.xml, app/src/main/res/layout/recycler_schedule_card_item.xml
* xml, java 소스 정리
* 카드 뷰에 시간, 제목, 내용 표시
=> 달력 날짜 클릭 시, 저장된 스케줄 카드뷰 형태 표시

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/playgilround/schedule/client/activity/AddScheduleActivity.java, app/src/main/java/com/playgilround/schedule/client/activity/LoginActivity.java, app/src/main/java/com/playgilround/schedule/client/activity/MainActivity.java, app/src/main/java/com/playgilround/schedule/client/activity/ScheduleCalendarActivity.java, app/src/main/java/com/playgilround/schedule/client/activity/ScheduleInfoActivity.java, app/src/main/java/com/playgilround/schedule/client/adapter/ScheduleCardAdapter.java, app/src/main/java/com/playgilround/schedule/client/model/ResponseMessage.java, app/src/main/java/com/playgilround/schedule/client/model/User.java, app/src/main/res/layout/activity_calendar.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_regist.xml, app/src/main/res/layout/app_bar_navigation.xml, app/src/main/res/layout/current_date.xml, app/src/main/res/layout/dialog_add_schedule.xml, app/src/main/res/layout/dialog_calendar.xml, app/src/main/res/layout/recycler_schedule_card_item.xml, app/src/main/res/values/strings.xml, build.gradle, gradle.properties
Androidx gradle 세팅,
ButterKnife gradle 세팅 후 LoginActivity 테스트
=> Androidx, Butterknife gradle 설정

app/src/main/java/com/playgilround/schedule/client/activity/ScheduleInfoActivity.java, app/src/main/java/com/playgilround/schedule/client/adapter/ScheduleCardAdapter.java, app/src/main/java/com/playgilround/schedule/client/model/ScheduleCard.java
* ScheduleInfoActivity.class ButterKnife 작업
* 카드 뷰 항목 클릭 시, 자세하게 표시를 위해 고유값 ( ID) 얻어오도록 수정
* 카드 뷰 항목 표시 할때 arrId, arrTime, arrTitle, arrDesc 를 ArrayList<ScheduleCard> 하나 통으로 수정.
=> 카드 뷰 관련, ScheduleInfoActivity ButterKnife

app/src/main/AndroidManifest.xml, app/src/main/java/com/playgilround/schedule/client/fragment/DetailScheduleFragment.java, app/src/main/res/layout/fragment_detail_schedule.xml
=> 디테일 카드뷰 애니메이션 추가

app/src/main/AndroidManifest.xml, app/src/main/java/com/playgilround/schedule/client/Schedule/ScheduleCalendarActivity.java, app/src/main/java/com/playgilround/schedule/client/Schedule/ScheduleCalendarPresenter.java, app/src/main/java/com/playgilround/schedule/client/Schedule/ScheduleContract.java, app/src/main/java/com/playgilround/schedule/client/activity/FriendActivity.java, app/src/main/java/com/playgilround/schedule/client/activity/MainActivity.java, app/src/main/java/com/playgilround/schedule/client/activity/ScheduleCalendarActivity.java, app/src/main/java/com/playgilround/schedule/client/singin/SignInActivity.java, app/src/main/res/layout/activity_friend.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values/strings.xml
* 친구 화면은 MaterialSearchBar 만 추가해놓은 상태,
* MVP Pattern 으로 ScheduleCalendarActivity 부터 작업진행 중
=> * 친구 화면에 MaterialSearchBar 추가, MVP Pattern 으로 변경 진행중 

app/src/main/java/com/playgilround/schedule/client/locationschedule/LocationScheduleActivity.java, app/src/main/java/com/playgilround/schedule/client/locationschedule/LocationScheduleContract.java, app/src/main/java/com/playgilround/schedule/client/locationschedule/LocationSchedulePresenter.java, app/src/main/java/com/playgilround/schedule/client/locationschedule/model/SearchLocationResult.java
=> LocationSchedule MVP 리펙토링

app/src/main/java/com/playgilround/schedule/client/signup/SignUpActivity.java, app/src/main/java/com/playgilround/schedule/client/signup/view/SignUpAdapter.java, app/src/main/res/layout/item_signup.xml, app/src/main/res/values/strings.xml
=> [#164266098] 백버튼 기능추가

app/src/main/java/com/playgilround/schedule/client/addschedule/AddScheduleActivity.java, app/src/main/java/com/playgilround/schedule/client/calendarschedule/CalendarScheduleActivity.java, app/src/main/java/com/playgilround/schedule/client/calendarschedule/CalendarSchedulePresenter.java, app/src/main/java/com/playgilround/schedule/client/infoschedule/InfoScheduleActivity.java, app/src/main/java/com/playgilround/schedule/client/manyschedule/ManyScheduleActivity.java, app/src/main/res/drawable/schedule_input_edit_text.xml, app/src/main/res/layout/activity_calendar.xml, app/src/main/res/layout/app_bar_navigation.xml, app/src/main/res/layout/content_navigation.xml, app/src/main/res/layout/dialog_calendar.xml, app/src/main/res/layout/recycler_many_schedule.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values/strings.xml
단일, 다중 스케줄 저장은
하단에 EditText 에 적어야 스케줄 저장가능.
Range Schedule 은 다이얼로그를 통해서 구성
=> 스케줄 저장 통일, Range schedule dialog 구성

app/src/main/java/com/playgilround/schedule/client/friend/FriendActivity.java, app/src/main/java/com/playgilround/schedule/client/friend/FriendContract.java, app/src/main/java/com/playgilround/schedule/client/friend/FriendPresenter.java, app/src/main/java/com/playgilround/schedule/client/model/ResponseMessage.java, app/src/main/java/com/playgilround/schedule/client/retrofit/BaseUrl.java, app/src/main/res/values-ko/strings.xml, app/src/main/res/values/strings.xml
Material Search Bar 연결 후, 유저 검색 처리
=> 유저 검색 api관련

app/src/main/java/com/playgilround/schedule/client/signup/SignUpContract.java, app/src/main/java/com/playgilround/schedule/client/signup/SignUpPresenter.java, app/src/main/java/com/playgilround/schedule/client/signup/view/SignUpAdapter.java
=> User.java 위치 변경

app/src/main/java/com/playgilround/schedule/client/signup/SignUpActivity.java, app/src/main/java/com/playgilround/schedule/client/signup/view/SignUpAdapter.java, app/src/main/res/layout/item_sign_up_birth.xml, app/src/main/res/values/styles.xml
SingUp 생년월일 View 추가
1. 기존 TextView 삭제
2. DatePicker View 추가
이슈(수정해야할 사항)
1. 선택 중인 년/월/일을 제외한 Text Color 변경
2. DatePicker 여러 번 터치 시 다른 View로 이동하는 이슈 수정
- currentPosition이 제때 +1 되지 않는 현상 수정
- SingUpAdapter.java의 Bind Function 수정: currentPosition이 TYPE_BIRTH일 경우 return
=> singup 생년월일 DatePicker 추가

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/playgilround/schedule/client/data/repository/UsersRepository.kt, app/src/main/java/com/playgilround/schedule/client/data/source/UsersDataSource.kt, app/src/main/java/com/playgilround/schedule/client/data/source/network/UsersRemoteDataSource.kt, app/src/main/java/com/playgilround/schedule/client/signin/SignInActivity.kt, app/src/main/java/com/playgilround/schedule/client/signin/SignInContract.kt, app/src/main/java/com/playgilround/schedule/client/signin/SignInPresenter.kt, app/src/main/res/values-ko/strings.xml, app/src/main/res/values/strings.xml, build.gradle, gradle.properties
=> [#162827199] 외부 로그인 추가
